version: "3"
services:
  mongodb-container-one:
    image: mongo:latest
    container_name: "mongodb-container-onee"
    ports:
      - 28000:27017
  springboot-with-mongodb-container-one:
    image: fares24/springboot-with-mongodb:v1
    container_name: springboot-with-mongodb-container-onee
    ports:
      - 8090:8081
    links:
      - mongodb-container-one